### ISSUE TITLE
Consider not retiring Lena

### ISSUE THREAD

**Issue by vojtechkral** [victorvde/jpeg2png#9]
... at least until someone presents credible evidence (ie. not just anecdotal) that this type of change actually helps matters ...

**Comment by teran-mckinney** [comment]
Yeah, nothing wrong with Lena. I would add things like memes and infographics, though.

Here's a perfect example of something that might benefit in PNG format: https://files.catbox.moe/2w4xd3.jpeg

**Comment by KarlAmort** [comment]
As credible evidence for the problems with using that image, I submit the fact that the people advocating for it are liable to also post anti-semitic memes, as @teran-mckinney has done above.

**Comment by vojtechkral** [comment]
@teran-mckinney Thanks for torpedoing my effort with that anti-semitic crap.

@MatthiasWinkelmann I agree with you that was an incredibly shitty reply from him. It's still anecdotal though.

**Comment by Bystroushaak** [comment]
Reverse stupidity is not intelligence, but chaos. I've seen many people react with reverse stupidity when triggered by latest batch of sjw nonsense.

**Comment by ghost** [comment]
I thought infographics would fair better, but they actually don't, at least not in file size from my testing.

**Comment by KarlAmort** [comment]
> @teran-mckinney Thanks for torpedoing my effort with that anti-semitic crap.
> 
> @MatthiasWinkelmann I agree with you that was an incredibly shitty reply from him. It's still anecdotal though.

@vojtechkral Thank you for re-establishing at least a lower bound of my believe in civilisation. And, yes, I'll grant that you drew a particularly bad hand with that hillbilly fascist. And yet it's unlikely to be a _completely random_ event that Mr. MAGA-McIncel shows up in this discussion.

Anyway... Enough ink has been spilled trying to show the technical merits of a change. Many people have sincerely stated that they consider the picture's use to be hostile to them. And, essentially, others have agreed that, yes, indeed, the continued use of the image is now entirely motivated by their intend to be hostile. 

There is no actual disagreement remaining.

**Comment by ghost** [comment]
I never had a chance to finish my previous comment.

The meme I shared was probably not a tasteful choice considering the typical audience on Github and most certainly of the offended parties. I'm since removed it, also because the file sizes I saw after conversion were far higher than I was expecting.

But let me get this straight. There's a movement to remove Lena from a project which has not had commits in over four years and was never all that popular to begin with. That, to me, seems like a witch hunt. I could understand much more if say the example was on libjpeg-turbo, something used extensively, actively, and with active development.

Instead, this project has somehow been targeted. I think it's entirely up to the author -- I have no real voice here and I know that. I have no actual bone in this other than my own opinion.

But, @MatthiasWinkelmann, you have demonstrated quite admirably the debate styles and zealous approach to censorship commonly seen from the certain group identified in the meme share I shared. It is comical to me how predictable such behavior is. You've resorted to name calling (Mr. MAGA-McIncel) over what is ultimately a silly picture.

How much more will you come for? Will you stop at Lena?

**Comment by vojtechkral** [comment]
> Many people have sincerely stated that they consider the picture's use to be hostile to them.

I believe that, but then again people are capable of sincerely considering pretty much anything hostile to them. Personally I find it often pretty hard to tell which grievances are justified and which aren't. People who request these changes have some kind of a shared rule-set or policy on how to judge these and what changes to request but it's not spelled anywhere explicitly and these people don't explain where they're coming from, what policy or philosophy they're following and whom they represent. It's typically just _"You should change $thing because otherwise you're harming $group"_.
